// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protobuf/generic_pci_api.proto

package generic_pci_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint32 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type Value32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value32) Reset() {
	*x = Value32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value32) ProtoMessage() {}

func (x *Value32) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value32.ProtoReflect.Descriptor instead.
func (*Value32) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{2}
}

func (x *Value32) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Value64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value64) Reset() {
	*x = Value64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value64) ProtoMessage() {}

func (x *Value64) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value64.ProtoReflect.Descriptor instead.
func (*Value64) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{3}
}

func (x *Value64) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddressValue32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint32 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Value   uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddressValue32) Reset() {
	*x = AddressValue32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressValue32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressValue32) ProtoMessage() {}

func (x *AddressValue32) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressValue32.ProtoReflect.Descriptor instead.
func (*AddressValue32) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddressValue32) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *AddressValue32) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddressValue64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint32 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Value   uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddressValue64) Reset() {
	*x = AddressValue64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_generic_pci_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressValue64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressValue64) ProtoMessage() {}

func (x *AddressValue64) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_generic_pci_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressValue64.ProtoReflect.Descriptor instead.
func (*AddressValue64) Descriptor() ([]byte, []int) {
	return file_protobuf_generic_pci_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddressValue64) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *AddressValue64) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protobuf_generic_pci_api_proto protoreflect.FileDescriptor

var file_protobuf_generic_pci_api_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1f, 0x0a, 0x07,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a,
	0x07, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x32,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x40, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x36, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0xa1, 0x02, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x50, 0x63,
	0x69, 0x41, 0x70, 0x69, 0x12, 0x3e, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x64, 0x33, 0x32, 0x12, 0x18,
	0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x33, 0x32, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x64, 0x36, 0x34, 0x12, 0x18,
	0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x36, 0x34, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07, 0x77, 0x72, 0x69, 0x74, 0x65, 0x33, 0x32, 0x12,
	0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x32,
	0x1a, 0x19, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x07, 0x77, 0x72, 0x69, 0x74, 0x65, 0x36, 0x34, 0x12, 0x1f, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x36, 0x34, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x6b, 0x6f, 0x6d, 0x2e, 0x74, 0x75,
	0x2d, 0x64, 0x61, 0x72, 0x6d, 0x73, 0x74, 0x61, 0x64, 0x74, 0x2e, 0x64, 0x65, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_generic_pci_api_proto_rawDescOnce sync.Once
	file_protobuf_generic_pci_api_proto_rawDescData = file_protobuf_generic_pci_api_proto_rawDesc
)

func file_protobuf_generic_pci_api_proto_rawDescGZIP() []byte {
	file_protobuf_generic_pci_api_proto_rawDescOnce.Do(func() {
		file_protobuf_generic_pci_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_generic_pci_api_proto_rawDescData)
	})
	return file_protobuf_generic_pci_api_proto_rawDescData
}

var file_protobuf_generic_pci_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_generic_pci_api_proto_goTypes = []interface{}{
	(*Response)(nil),       // 0: generic_pci_api.Response
	(*Address)(nil),        // 1: generic_pci_api.Address
	(*Value32)(nil),        // 2: generic_pci_api.Value32
	(*Value64)(nil),        // 3: generic_pci_api.Value64
	(*AddressValue32)(nil), // 4: generic_pci_api.AddressValue32
	(*AddressValue64)(nil), // 5: generic_pci_api.AddressValue64
}
var file_protobuf_generic_pci_api_proto_depIdxs = []int32{
	1, // 0: generic_pci_api.GenericPciApi.read32:input_type -> generic_pci_api.Address
	1, // 1: generic_pci_api.GenericPciApi.read64:input_type -> generic_pci_api.Address
	4, // 2: generic_pci_api.GenericPciApi.write32:input_type -> generic_pci_api.AddressValue32
	5, // 3: generic_pci_api.GenericPciApi.write64:input_type -> generic_pci_api.AddressValue64
	2, // 4: generic_pci_api.GenericPciApi.read32:output_type -> generic_pci_api.Value32
	3, // 5: generic_pci_api.GenericPciApi.read64:output_type -> generic_pci_api.Value64
	0, // 6: generic_pci_api.GenericPciApi.write32:output_type -> generic_pci_api.Response
	0, // 7: generic_pci_api.GenericPciApi.write64:output_type -> generic_pci_api.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_generic_pci_api_proto_init() }
func file_protobuf_generic_pci_api_proto_init() {
	if File_protobuf_generic_pci_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_generic_pci_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_generic_pci_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_generic_pci_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_generic_pci_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_generic_pci_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressValue32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_generic_pci_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressValue64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_generic_pci_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_generic_pci_api_proto_goTypes,
		DependencyIndexes: file_protobuf_generic_pci_api_proto_depIdxs,
		MessageInfos:      file_protobuf_generic_pci_api_proto_msgTypes,
	}.Build()
	File_protobuf_generic_pci_api_proto = out.File
	file_protobuf_generic_pci_api_proto_rawDesc = nil
	file_protobuf_generic_pci_api_proto_goTypes = nil
	file_protobuf_generic_pci_api_proto_depIdxs = nil
}
